cog predict \
    -i run_name="xander_xander_5.zip_000_3113" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_5.zip_001_3114" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_002_3114" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_003_3114" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_5.zip_004_3115" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_005_3116" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_006_3118" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_5.zip_007_3118" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_5.zip_008_3121" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_5.zip_009_3126" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_010_3131" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_011_3147" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_012_3153" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_5.zip_013_3156" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_2.zip_014_3208" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_2.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="xander_xander_5.zip_015_3214" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/xander_5.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

