cog predict \
    -i run_name="dc" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i checkpointing_steps="1200" \
    -i concept_mode="face" \
    -i debug="True" \
    -i left_right_flip_augmentation="False" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/dc.zip" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i l1_penalty="0.1" \
    -i ti_lr=3e-3 \
    -i resolution=1024 \
    -i seed="0" \
    -i train_batch_size="2"  