cog predict \
    -i run_name="faces_banny_small.zip_001_3546" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_002_3546" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_003_3546" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_004_3547" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_005_3547" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_006_3547" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_007_3549" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_008_3553" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_009_3555" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_010_3555" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_011_3559" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_012_3576" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="True" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="3e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_013_3590" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.001" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_014_3596" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="0" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

cog predict \
    -i run_name="faces_banny_small.zip_015_3619" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="30" \
    -i checkpointing_steps="1200" \
    -i concept_mode="object" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i is_lora="True" \
    -i left_right_flip_augmentation="True" \
    -i lora_rank="6" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/banny_small.zip" \
    -i lora_weight_decay="0.005" \
    -i max_train_steps="1200" \
    -i prodigy_d_coef="0.9" \
    -i resolution=1024 \
    -i seed="0" \
    -i ti_lr="1e-3" \
    -i ti_weight_decay="1e-4" \
    -i train_batch_size="2"  

