cog predict \
    -i run_name="ti_tiny_lora_steel.zip_000_673" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="1.0" \
    -i lora_rank="24" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/steel.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_001_673" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.1" \
    -i lora_rank="24" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="1.0" \
    -i resolution=1024 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_steel.zip_002_673" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.3" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/steel.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="1.0" \
    -i resolution=1024 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_steel.zip_003_673" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.1" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/steel.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="0.5" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_004_674" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.3" \
    -i lora_rank="24" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_005_675" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="1.0" \
    -i lora_rank="24" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="1.0" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_006_684" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="1.0" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="0.5" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_007_687" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.1" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="0.5" \
    -i resolution=1024 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_steel.zip_008_689" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.1" \
    -i lora_rank="24" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/steel.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="1.0" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_009_692" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="1.0" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="1.0" \
    -i resolution=1024 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_steel.zip_010_695" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="1.0" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/steel.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="1.0" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_011_697" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.1" \
    -i lora_rank="24" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="0.5" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_mam.zip_012_728" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.3" \
    -i lora_rank="12" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/mam.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="1.0" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

cog predict \
    -i run_name="ti_tiny_lora_steel.zip_013_818" -i caption_prefix="" \
    -i mask_target_prompts="" \
    -i augment_imgs_up_to_n="20" \
    -i caption_prefix="a photo of TOK" \
    -i checkpointing_steps="700" \
    -i concept_mode="face" \
    -i debug="True" \
    -i hard_pivot="False" \
    -i l1_penalty="0.1" \
    -i left_right_flip_augmentation="False" \
    -i lora_param_scaler="0.3" \
    -i lora_rank="24" \
    -i lora_training_urls="https://storage.googleapis.com/public-assets-xander/A_workbox/lora_training_sets/steel.zip" \
    -i lora_weight_decay="0.002" \
    -i max_train_steps="600" \
    -i prodigy_d_coef="0.5" \
    -i resolution=896 \
    -i seed="0" \
    -i train_batch_size="4"  

